### PR TITLE
Update configure_init_script.pp

### PR DESCRIPTION
**Pull request by slantedvision**
By adding a scoped variable import, we are able to use the variables mentioned in the ERB file.  This will generate the desired file and contents.

### CODE REVIEW

**Comment by metmajer** [comment]
Thanks @slantedvision for this PR! The problem with your change is that almost every component (server, collector, etc.) requires a different set of attributes inside the init.d scripts. This explains the use of the 'params' hash together with EPP templates (which breaks 3.8 support unfortunately). The params which you have added in your PR are very specific to the Dynatrace Collector and should not be in the parameter list of `configure_init_script`.

**Comment by metmajer** [comment]
As I understand it, the scope of the template invocation includes only those variables which exist in `configure_init_script`. What I eventually want to achieve is to broaden the scope so that variables known to `collector` can be used inside the template. What's your take on this? Otherwise I'll have to find some dirty solution (and I fear this is why EPP templates have been invented *sigh*).

**Comment by slantedvision** [comment]
The ERB should have the scope changed to actually dive into the params key to capture the values.  I'll have one more commit but the jist will be to replace variables in the erb with the params lookup.

DT_OPTARGS="-listen <%= @params["agent_port"] %> -server <%= @params["server_hostname"] %>:<%= @params["server_port"] %><% if @params["jvm_xms"] %> -Xms<%= @params["jvm_xms"] %><% end %><% if @params["jvm_xmx"] %> -Xmx<%= @params["jvm_xmx"] %><% end %><% if @params["jvm_perm_size"] %> -XX:PermSize=<%= @params["jvm_perm_size"] %><% end %><% if @params["jvm_max_perm_size"] %> -XX:MaxPermSize=<%= @params["jvm_max_perm_size"] %><% end %>"

**Comment by slantedvision** [comment]
At some point I'll figure out how to update my fork with that and take out the edits I've put in place so far.

**Comment by metmajer** [comment]
Hmm... why didn't I think of accessing the params hash from inside the templates? :+1:

If you don't commit something by EOD, I'll provide the solution and merge to the master tomorrow morning. I have a customer waiting for a fix. Thanks for the intellectual exchange of ideas! :-)

**Comment by slantedvision** [comment]
I believe I've been able to stagger my way to a push to the fork with the updates.  Sorry to plaster my commit message all over the place.  If your other customer is watching this fork, I'm so sorry you had to witness this :)

**Comment by metmajer** [comment]
Great. Will expand the commit to the entire module and make sure it's tested before I merge to trunk. Thanks @slantedvision!

**Pull request merged**
